var asseruil = require('assert')
var TypeArray = require('../build/index.js').TypeArray
var array = new TypeArray()
array.push(4)
array.push(5)
array.push(6)
array.push(7)
var iterator = array.entries()
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
iterator.init()
console.log(iterator.next().value)