var asseruil = require('assert')
var TypesArray = require('../build/index.js').TypesArray
var array = new TypesArray()
array.push(4)
array.push(5)
array.push(6)
array.push(7)
var iterator = array.entries()
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
console.log(iterator.next().value)
iterator.init()
console.log(iterator.next().value)